### ISSUE TITLE
Support Ability for US or updating the API_BASE_URI

### ISSUE THREAD

**Issue by stboch** [BaQs/pyEzviz#4] opened 2020-03-23 03:13 UTC
US Ezviz customers must use apiius.ezvizlife.com instead of eu.
The redirect activity is supported but there appears to be an issue during the login process much easier to just support changing the API_BASE_URI 

Thanks!

**Comment by sreknob** [comment] 2020-03-23 15:12
Yes, I've found the same thing in Canada --> https://github.com/home-assistant/core/issues/32944#issuecomment-602296912

Even better would be to detect the redirection and use that so that nothing needs to be hard-coded.

**Comment by BaQs** [comment] 2020-03-23 19:48
Thx for the feedback!
So I think the pypi module would have to be adapted?
Please feel free to patch

**Comment by sreknob** [comment] 2020-03-24 00:27
I suppose there are two options I can think of
1. use `requests` and grab the [redirection history](https://requests.readthedocs.io/en/master/user/quickstart/#redirection-and-history) after hitting the api url and store that at the base. The only problem that I can think of is that I believe that the redirection happens after the initial auth when using a browser. Not sure how to deal with that yet.
2. Use something like ipapi.co to lookup the country and then use that for region lookup. Probably a bad solution.
Just brainstorming....

**Comment by BaQs** [comment] 2020-03-24 12:01
I’m not a big fan of option 2.
I saw other integrations where the user had to fulfill “us”, “EU” ad an option for instance. We could simply propose this?

**Comment by stboch** [comment] 2020-03-24 15:18
Hey sorry my python skills trying to get this into the way you wrote your app is causing my some struggle but you might make this go faster...

When a user "/v3/user/login" to the wrong api server the following JSON blob is returned. 
`{"meta":{"code":1100,"message":"客户端需要重定向用户请求域名(海外)","moreInfo":null},"loginArea":{"apiDomain":"apiius.ezvizlife.com","webDomain":"ius.ezvizlife.com","areaName":"USA","areaId":314}}`

so basically 
`try:
            response_json = req.json()
            if response_json["meta"]["code"] == 1100:
                API_BASE_URI = "https://" + str(response_json["loginArea"]["apiDomain"])
                ### retrigger login ###a
                self.login()
            else:
                logging.info("Entering Else statement")
                sessionId = str(response_json["loginSession"]["sessionId"])
                if not sessionId:
                    raise PyEzvizError("Login error: Please check your username/password: %s ", str(re
q.text))
                    self._sessionId = sessionId`

**Comment by BaQs** [comment] 2020-03-25 20:52
New version released: 0.1.5.4 . Should be fine then

**Comment by stboch** [comment] 2020-03-26 13:54
@BaQs So 2 things, 
1 api_domain is the full url + tld so I made a quick fix 
2. but what is happening is the Login is fine, but the follow on requests keep reverting back to the URL and just loops between the function of "Device" then back to login ... etc...

**Comment by Shlyakhoff** [comment] 2020-04-09 12:45
Let me please know how to change api_domain?

**Comment by Shlyakhoff** [comment] 2020-04-16 16:16
Hi! I switch the 
EU_API_DOMAIN = "i"
API_BASE_TLD = "ezvizru.com"

After 
pyezviz -u USERNAME -p PASS --debug devices status 
I can see that 3 from 5 cameras logged but the process ends with following strings:
DEBUG:urllib3.connectionpool:https://i.ezvizru.com:443 "POST /api/device/queryAlgorithmConfig HTTP/1.1" 200 None
'NoneType' object is not subscriptable

Something wrong with the code? Any ideas?

Logger: homeassistant.components.camera
Source: components/ezviz/camera.py:50
Integration: Камера (documentation, issues)
First occurred: 18:42:32 (1 occurrences)
Last logged: 18:42:32

Error while setting up ezviz platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ezviz/camera.py", line 50, in setup_platform
    cameras = ezviz_client.load_cameras()
  File "/usr/local/lib/python3.7/site-packages/pyezviz/client.py", line 197, in load_cameras
    cameras.append(camera.status())
  File "/usr/local/lib/python3.7/site-packages/pyezviz/camera.py", line 97, in status
    'follow_move': self._switch[TYPE_FOLLOW_MOVE]['enable'],
KeyError: 25

**Comment by Shlyakhoff** [comment] 2020-05-01 08:38
Let me update my experience...
I finaly got the half-working ezviz component when I switched the server to https://apiirus.ezvizru.com and deleted 3 from 5 cameras. I don't know why but all [MiniO - C2C ](https://ezviz.ru/cctv/c2c) cams didn't connected and showed "KeyError: 25", whereas [Husky Air - C3W](https://ezviz.ru/cctv/c3w) cams registred without any errors but any ezviz's services in the Home assistant I didn't find.

pyezviz -u LOGIN -p PASS --debug devices status
      serial         name  status  ...      local_ip  local_rtsp_port  detection_sensibility
0  serial_cam1  Frontstreet       1  ...  192.168.1.71                0                      1
1  serial_cam2  Backstreet       1  ...  192.168.1.65                0                      1

pyezviz -u LOGIN -p PASS camera --serial serial_cam1 status
{
  "serial": "serial_cam1",
  "name": "Frontstreet",
  "status": 1,
  "device_sub_category": "Husky Air",
  "privacy": false,
  "audio": true,
  "ir_led": false,
  "state_led": false,
  "follow_move": false,
  "alarm_notify": true,
  "alarm_sound_mod": "Disabled",
  "encrypted": false,
  "local_ip": "192.168.1.71",
  "local_rtsp_port": 0,
  "detection_sensibility": "1"
}
@BaQs, could you please help me to solve the problem?

**Comment by SouthButovo** [comment] 2020-08-25 10:42
> Let me update my experience...
> I finaly got the half-working ezviz component when I switched the server to https://apiirus.ezvizru.com and deleted 3 from 5 cameras. I don't know why but all [MiniO - C2C ](https://ezviz.ru/cctv/c2c) cams didn't connected and showed "KeyError: 25", whereas [Husky Air - C3W](https://ezviz.ru/cctv/c3w) cams registred without any errors but any ezviz's services in the Home assistant I didn't find.
> 
> pyezviz -u LOGIN -p PASS --debug devices status
> serial name status ... local_ip local_rtsp_port detection_sensibility
> 0 serial_cam1 Frontstreet 1 ... 192.168.1.71 0 1
> 1 serial_cam2 Backstreet 1 ... 192.168.1.65 0 1
> 
> pyezviz -u LOGIN -p PASS camera --serial serial_cam1 status
> {
> "serial": "serial_cam1",
> "name": "Frontstreet",
> "status": 1,
> "device_sub_category": "Husky Air",
> "privacy": false,
> "audio": true,
> "ir_led": false,
> "state_led": false,
> "follow_move": false,
> "alarm_notify": true,
> "alarm_sound_mod": "Disabled",
> "encrypted": false,
> "local_ip": "192.168.1.71",
> "local_rtsp_port": 0,
> "detection_sensibility": "1"
> }
> @BaQs, could you please help me to solve the problem?

Are you solve the problem for RU server?

**Comment by RenierM26** [comment] 2020-11-29 12:59
'NoneType' object is not subscriptable happens when there's an undefined value for an array or data type. Community members have fixed this problem under pull requests. 

I thinks it's mostly caused by detection sensitivity returning an unknown value. (code expects an integer)?

**Comment by RenierM26** [comment] 2021-01-27 05:18
Hi There, 

This issue was fixed in the latest release.

**Closed by RenierM26** 2021-01-27 05:18 UTC
